_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 106
            "2":
                - 1
                - 11
                - 49
                - 106
            "3":
                - 13
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "6": 4.44.0
            "12": 0.20.1
            "13": linux-x86_64
